'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Recursively copy every file under srcDir into dstDir, skipping any that
 * already exist at the destination. Never overwrites, never deletes.
 *
 * @param {string} srcDir
 * @param {string} dstDir
 * @returns {string[]} destination paths that were created
 */
function copyMissingFiles(srcDir, dstDir) {
  const copied = [];
  if (!fs.existsSync(srcDir)) return copied;
  // Dogfooding case: the app IS the project, so source and destination are the
  // same tree and there is nothing to do.
  if (path.resolve(srcDir) === path.resolve(dstDir)) return copied;

  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dst = path.join(dstDir, entry.name);
    if (entry.isDirectory()) {
      copied.push(...copyMissingFiles(src, dst));
    } else if (entry.isFile() && !fs.existsSync(dst)) {
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      fs.copyFileSync(src, dst);
      copied.push(dst);
    }
  }
  return copied;
}

/**
 * Ensure the .ombutocode/ directory structure exists in the target project.
 * Creates subdirectories, copies template files from APP_ROOT if not present,
 * and generates a .gitignore for runtime files.
 *
 * @param {string} projectRoot - The target project root directory
 * @param {string} appRoot - Ombuto Code's own installation directory
 */
function ensureOmbutocodeStructure(projectRoot, appRoot) {
  const ombutocodeDir = path.join(projectRoot, '.ombutocode');

  // Required subdirectories
  const subdirs = [
    'planning',
    'data',
    'data/tickets',
    'features',
    'templates',
    'codingagents',
    'logs',
    'run-output'
  ];

  for (const sub of subdirs) {
    const dirPath = path.join(ombutocodeDir, sub);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  }

  // Copy template files from APP_ROOT/.ombutocode/templates/ if not present.
  // Recursive: templates/skills/ and templates/mockups/ are sub-folders, and a
  // flat copy would leave every project stuck with whatever templates shipped
  // on the day it was created.
  const templateSrc = path.join(appRoot, '.ombutocode', 'templates');
  const templateDst = path.join(ombutocodeDir, 'templates');
  copyMissingFiles(templateSrc, templateDst);

  // Seed docs/Skills/<Category>/<skill>.md from the skill templates. Only ever
  // adds files that aren't there — user edits and deletions are never undone
  // for a skill that already exists, but newly shipped skills reach existing
  // projects instead of waiting for an initombuto reset.
  copyMissingFiles(
    path.join(templateDst, 'skills'),
    path.join(projectRoot, 'docs', 'Skills')
  );

  // Copy OMBUTOCODE_ENGINEERING_GUIDE.md to target .ombutocode/ if not present
  const guideSrc = path.join(appRoot, '.ombutocode', 'OMBUTOCODE_ENGINEERING_GUIDE.md');
  const guideDst = path.join(ombutocodeDir, 'OMBUTOCODE_ENGINEERING_GUIDE.md');
  if (fs.existsSync(guideSrc) && !fs.existsSync(guideDst)) {
    fs.copyFileSync(guideSrc, guideDst);
  }

  // Create empty backlog.yml from template if not present
  const backlogPath = path.join(ombutocodeDir, 'planning', 'backlog.yml');
  if (!fs.existsSync(backlogPath)) {
    const backlogTemplate = path.join(templateDst, 'backlog.yml');
    if (fs.existsSync(backlogTemplate)) {
      fs.copyFileSync(backlogTemplate, backlogPath);
    } else {
      // Minimal backlog if no template available
      fs.writeFileSync(backlogPath, 'version: 1\nupdated_at: ""\ntickets: []\n', 'utf8');
    }
  }

  // Create .ombutocode/.gitignore for runtime file exclusions
  const gitignorePath = path.join(ombutocodeDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    const gitignoreContent = [
      '# Runtime files (auto-generated by Ombuto Code)',
      'logs/',
      'run-output/',
      'codingagent-state.json',
      'data/*.db',
      'data/tickets/*.json',
      'data/tickets/*.tmp',
      'planning/archive.db',
      ''
    ].join('\n');
    fs.writeFileSync(gitignorePath, gitignoreContent, 'utf8');
  }
}

module.exports = { ensureOmbutocodeStructure, copyMissingFiles };
